// src/components/Header/RegionInput.jsx
import React from 'react';
import data from '../../utils/data.js';

const regions = data.map(value => ({
    name: value.region,
    description: value.description
}));

export default function RegionInput({ value, onChange }) {
    return (
        <select
            value={value}
            onChange={(e) => onChange(e.target.value)}
            className="bg-white border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-indigo-500 focus:border-indigo-500 block p-2.5 shadow-sm"
        >
            {regions.map((region) => (
                <option key={region.name} value={region.name}>
                    {region.description}
                </option>
            ))}
        </select>
    );
}

// src/components/Header/RegionInput.svelte
<script>
    import data from '../../utils/data.js'

    export let value

    const regions = data.map(value => ({
        name: value.region,
        description: value.description
    }))
</script>

<style>
    select {
        color: #eee;
        border-color: #e76d0c #e15500 #e15500;
        background-color: white;
        background-image: linear-gradient(180deg,#f67c1b 0,#e15500);
    }
    option {
        color: black;
    }
</style>

<select bind:value={value}>
    {#each regions as region}
        <option value={region.name}>
            {region.description}
        </option>
    {/each}
</select>
